pipeline:
  test:
    image: python:3.6
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=url
      - POSTGRES_PASSWORD=secret
    commands:
      - pip install pipenv
      - cd app
      - pipenv install --system
      - python app.py &
      - sleep 5
      - "curl -s localhost:8000/health | grep 'true'"
    when:
      branch: [master, cicd]

  telegram:
    image: appleboy/drone-telegram
    message: >
      build {{build.number}} {{build.status}}.
    secrets: [ telegram_token, telegram_to ]

  publish:
    image: plugins/docker:17.10
    repo: cuongnv23/url-shortener-app
    dockerfile: app/Dockerfile
    context: app
    secrets: [ docker_username, docker_password ]
    tag: latest
    when:
      branch: [ master ]

services:
  postgres:
    image: cuongnv23/url-shortener-db
