pipeline:
  test:
    image: python:3.6
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=url
      - POSTGRES_PASSWORD=secret
    commands:
      - apt-get install -y jq
      - pip install pipenv
      - cd app
      - pipenv install --system
      - python app.py &
      - sleep 5
      - [[ `curl -s localhost:8000/health | jq '.db_access_ok'` == 'true' ]]
    when:
      branch: [master, cicd]

services:
  postgres:
    image: cuongnv23/url-shortener-db
