---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: redirects
  POSTGRES_HOST: postgres-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default: |
    server {
          listen 80 default_server;
          server_name _;
          
          proxy_request_buffering off;
          client_max_body_size 0;
          client_body_buffer_size 1024k;
          client_body_timeout 120s;
          proxy_buffering off;

          location / {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $http_host;
              proxy_pass http://app:8000;
          }

          location /static/ {
              root /var/www/;
          }
    }
